#!/bin/sh
set -e
. /usr/share/debconf/confmodule

if [ "$1" != "upgrade" ]; then

    update-alternatives --remove libblis.so.@SOVER@-@DEB_HOST_MULTIARCH@ \
                        /usr/lib/@DEB_HOST_MULTIARCH@/@SUBDIR@/libblis.so.@SOVER@

    update-alternatives --remove libblas.so.3-@DEB_HOST_MULTIARCH@ \
                        /usr/lib/@DEB_HOST_MULTIARCH@/@SUBDIR@/libblas.so.3

fi

#DEBHELPER#
exit 0
